# Generated by Django 3.0.8 on 2020-08-07 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='العنوان')),
                ('description', models.CharField(max_length=100, verbose_name='الوصف')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='الاسلك')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, verbose_name='الصورة', width_field='width_field')),
                ('height_field', models.IntegerField(default=0, verbose_name='الطول')),
                ('width_field', models.IntegerField(default=0, verbose_name='العرض')),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False, verbose_name='مسودة')),
                ('read_time', models.TimeField(blank=True, null=True, verbose_name='زمن القراءة')),
                ('publish', models.DateField(verbose_name='زمن الانشاء')),
                ('publish_at', models.DateTimeField(auto_now_add=True, verbose_name='زمن النشر')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_user', to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
            options={
                'ordering': ['-publish_at', '-updated'],
            },
        ),
    ]
