# Generated by Django 3.0.8 on 2020-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200806_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_us',
            field=models.TextField(max_length=200, verbose_name=' نبذه عنك'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/', verbose_name=' الصورة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name=' رقم الهاتف'),
        ),
    ]
