# Generated by Django 3.0.8 on 2020-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_member',
            field=models.BooleanField(default=False, verbose_name='عضو مميز'),
        ),
    ]
