# Generated by Django 3.0.8 on 2020-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200806_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=' الايميل'),
        ),
    ]
