# Generated by Django 3.0.8 on 2020-08-09 19:03

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200806_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='about',
            field=mdeditor.fields.MDTextField(verbose_name='المحتوي'),
        ),
    ]
