# Generated by Django 3.0.8 on 2020-08-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200809_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
